sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy3"

env:
  - DJANGO="django==2.0.7"
  - DJANGO="django==1.11.14"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install pycodestyle
  - pip install coveralls

script: coverage run --source=toolware manage.py test

after_success:
  coveralls

