sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

env:
  - DJANGO="django==2.0.2"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install pycodestyle
  - pip install coveralls

before_script:
  - bash formatter.sh

script: coverage run --source=toolware manage.py test

after_success:
  coveralls
